import localFont from "next/font/local";
import "./globals.css";

const buenosAiresRegular = localFont({ src: "../public/fonts/buenos-aires-regular.ttf" })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={buenosAiresRegular.className}>
        {children}
      </body>
    </html>
  );
}
